name: image-classifier
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - pytest
  - pyqt
  - pip:
      - medmnist
      - opencv-python
